# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.6.0
_src_path: gh:algorandfoundation/algokit-fullstack-template
author_email: your@email.tld
author_name: Your-Name
cloud_provider: netlify
contract_name: hello_world
deployment_language: typescript
ide_vscode: true
preset_name: production
project_name: tenx_fullstack
python_linter: flake8
use_dispenser: true
use_github_actions: true
use_python_black: true
use_python_mypy: true
use_python_pip_audit: true
use_typescript_jest: true

